### ISSUE TITLE
Not supporting large genome

### ISSUE THREAD

**Issue by radio1988** [atulkakrana/PHASIS#5] opened 2017-04-22 17:30 UTC
Hello, thanks for creating this package for phase siRNA analysis. We are working with a large genome (17 Gb), which is more than the 4 billion bp allowed for the 32bit indexing of bowtie. As a result, bowtie treats it as 'large genome' and creates 'ebwtl' files rather than 'ebwt' files. And phasdetect reports an error (attached). Is there a way to work with large genome in phasis? Thanks!

#### Fn: checkLibs ###########################
--Python v3.0 or higher          : found
--Perl v5.14 or higher           : found
--Bowtie (v1)                    : found
--Scalar::Util (perl)            : found
--Data::Dumper (perl)            : found
--Parallel::ForkManager (perl)   : found
--Getopt::Long (perl)            : found

#### Fn: Settings Reader #####################
User Input runType               : S
User Input reference location    : /home/wheat_0421/ABD_Genome.20170209.fa
User Input Libs                  : /home/wheat_0421/WheatsRNA_tagcount.txt
user library format              : T
User Input for phase length      : 21
User Input index location        : None
User Input for min. sRNA depth   : 3
User Input distance b/w clusters : 300

#### 7 cores assigned to one lib ############

This is first run - create index

#### Fn: indexBuilder #######################
Reference file located - Preparing to create index
PHASER uses FASTA header as key for identifying the phased loci
Cleaning header '/home/wheat_0421/ABD_Genome.20170209.fa' reference FASTA file
Fasta file with reduced header: '/home/wheat_0421/ABD_Genome.20170209.clean.fa' with total entries 10663309 is prepared
There were 113398 entries found with empty sequences and were removed

**Deleting old index 'folder' !!!!!!!!!!!**
If its a mistake cancel now by pressing ctrl+D and continue from index step by turning off earlier steps- You have 2 seconds
Creating index of cDNA/genomic sequences:/home/wheat_0421/index/ABD_Genome.20170209.clean**

Generating MD5 hash for reference
Generating MD5 hash for Bowtie index
File extension for index couldn't be determined properly
It could be an issue from Bowtie
This needs to be reported to 'PHASwroks' developer - Script will exit

**Comment by atulkakrana** [comment] 2017-04-23 00:32
Hi Radio,

Thank you for using *PHASIS*. Are you using the latest version of PHASIS (v3.2)? We added the support for larger genomes in this final [release](https://github.com/atulkakrana/PHASIS/releases).

Atul

**Comment by radio1988** [comment] 2017-04-23 02:48
Thank you for the quick reply! We used "PHASIS-3.2". bowtie version 1.1.2

**Comment by radio1988** [comment] 2017-04-23 02:51
The program was run on Bio-Linux (Ubuntu 16.04.2 LTS) with 32GB RAM.

**Comment by atulkakrana** [comment] 2017-04-23 15:24
Thanks for checking. We tested *PHASIS* on "Wheat" genome and it worked fine. Could you please paste here the contents of 'index' folder generated by *PHASIS*? I will see what's going wrong and get back to you tomorrow.

Atul

**Comment by radio1988** [comment] 2017-04-23 18:31
in the /home/wheat_0421/index folder, there are the following files:

ABD_Genome.20170209.clean.1.ebwtl  ABD_Genome.20170209.clean.rev.1.ebwtl
ABD_Genome.20170209.clean.2.ebwtl  ABD_Genome.20170209.clean.rev.2.ebwtl
ABD_Genome.20170209.clean.3.ebwtl  ABD_Genome.20170209.clean.4.ebwtl

==========
If I run ' python3 phasdetect' again in the same folder right now. It showes me:


#### Checking user ###########################
Hello 'rui' - Please report issues at: https://github.com/atulkakrana/PHASIS/issues

#### Fn: checkLibs ###########################
--Python v3.0 or higher          : found
--Perl v5.14 or higher           : found
--Bowtie (v1)                    : found
--Scalar::Util (perl)            : found
--Data::Dumper (perl)            : found
--Parallel::ForkManager (perl)   : found
--Getopt::Long (perl)            : found

#### Fn: Settings Reader #####################
User Input runType               : S
User Input reference location    : /home/wheat_0421/ABD_Genome.20170209.fa
User Input Libs                  : /home/wheat_0421/WheatsRNA_tagcount.txt
user library format              : T
User Input for phase length      : 21
User Input index location        : None
User Input for min. sRNA depth   : 3
User Input distance b/w clusters : 300

#### 7 cores reserved for analysis ##########
#### 7 cores assigned to one lib ############

Generating MD5 hash for current reference file
#### Fn: memReader ############################
Current reference hash           : 1e246abfba7c91344dba5e3696e8ed85
Traceback (most recent call last):
  File "phasdetect.py", line 1008, in <module>
  File "phasdetect.py", line 894, in main
NameError: name 'existRefHash' is not defined

**Comment by radio1988** [comment] 2017-04-24 16:54
Can you tell me which version of bowtie you are using? Maybe I can try the same version. Thanks!

**Comment by atulkakrana** [comment] 2017-04-24 18:42
Rui,

It seems there is a minor regression in version 3.2, which is affecting index extension determination part. I have issued the fix this morning, and it is being tested internally. We will release an updated script ASAP - maybe by the end of today or tomorrow morning. 

Sorry for the inconvenience. 

Atul

**Comment by radio1988** [comment] 2017-04-24 22:09
This sounds great. Thanks for the prompt actions!

**Comment by atulkakrana** [comment] 2017-04-25 14:35
Hi Radio,

Thank you for your patience. Wheat has a large genome, therefore, it took us some time to test the fix. I have pushed the fix to the latest [version]( https://github.com/atulkakrana/PHASIS/releases).

Please note that the first run will take a lot of time, due to index preparation step. After that, all the analyses will be quick. Also, I would suggest you to input the libraries as a list instead of concatenating them to one file as the latter might add a few false positives to your result.

Atul

**Comment by radio1988** [comment] 2017-04-26 04:12
Thank you so much for the quick update. I've started the Phasis3.3. I'll update you how it goes, hopefully tomorrow. 

Radio

**Comment by radio1988** [comment] 2017-04-26 18:36
Hi Atul, 

Thanks a lot for the update on PHASIS. The index problem seems fixed. But I ran into a new problem. We ran this version of PHASIS on a single Lib file just to test if the program work.

#### Checking user ###########################
Hello 'rui' - Please report issues at: https://github.com/atulkakrana/PHASIS/issues

#### Fn: checkLibs ###########################
--Python v3.0 or higher          : found
--Perl v5.14 or higher           : found
--Bowtie (v1)                    : found
--Scalar::Util (perl)            : found
--Data::Dumper (perl)            : found
--Parallel::ForkManager (perl)   : found
--Getopt::Long (perl)            : found

#### Fn: Settings Reader #####################
User Input runType               : S
User Input reference location    : /home/rui/sowmya/wheat_0425/ABD_Genome.20170209.fa
User Input Libs                  : /home/rui/sowmya/wheat_0425/WheatsRNA_tagcount.txt
user library format              : T
User Input for phase length      : 21
User Input index location        : None
User Input for min. sRNA depth   : 3
User Input distance b/w clusters : 300

#### 7 computing core(s) reserved for analysis ##########
#### 7 computing core(s) assigned to one lib ############

This is first run - create index

#### Fn: indexBuilder #######################
Reference file located - Preparing to create index
phasdetect uses FASTA header as key for identifying the phased loci
Caching '/home/rui/sowmya/wheat_0425/ABD_Genome.20170209.fa' reference FASTA file
Fasta file with reduced header: '/home/rui/sowmya/wheat_0425/ABD_Genome.20170209.clean.fa' with total entries 10663309 is prepared
There were 113398 entries found with empty sequences and were removed

**Deleting old index 'folder' !!!!!!!!!!!**
Creating index of cDNA/genomic sequences:/home/rui/sowmya/wheat_0425/index/ABD_Genome.20170209.clean**

Generating MD5 hash for Bowtie index

@genomehash:1e246abfba7c91344dba5e3696e8ed85 | @indexhash:fc858c066992ccf6fe7785e0caca9648
Index prepared:/home/rui/sowmya/wheat_0425/index/ABD_Genome.20170209.clean

nprocPP                          : 1
Wed Apr 26 03:53:07 2017: Phasing analysis begins...
Wed Apr 26 03:53:07 2017: seq conversion is done...
Wed Apr 26 03:53:07 2017: aligning...
Wed Apr 26 03:53:07 2017: script version is 1..
sh: 1: cannot create ./phased_04_25_21_06//home/rui/sowmya/wheat_0425/WheatsRNA_tagcount.txt.9kzWD8MkQA_: Directory nonexistent
Cannot open the bowtie outputed DATA at /home/rui/.phasis/phasclust.MUL.v2.pl line 109.
Wed Apr 26 03:53:07 2017: aligning is done

#### Fn: phaser #############################
sRNA library located - Running phasing analysis
/home/rui/sowmya/wheat_0425/WheatsRNA_tagcount.txt
** Problem with Phasing script - Return code not 0

**Comment by radio1988** [comment] 2017-04-26 18:38
I installed PHASIS3.3 by downloading the gz file, decompress it, then run sh install.sh. It was reported to be successful, as I already installed the prerequisites before.

**Comment by atulkakrana** [comment] 2017-04-27 01:50
Hi Radio,

I am sorry that you are seeing these issues. But this one seems to be specific to your system. Do you have binaries in same folder as genome and sRNA library? All binaries and input files need to be in same folder. 

Also, could you please check the output of "~" on your system? Please paste the output of this command:
```~ && pwd```

Atul

**Comment by radio1988** [comment] 2017-04-27 04:21
Thanks! I have put these files under: /home/rui/sowmya/wheat_0425

The phasis.set I had yesterday:
@reference              = /home/rui/sowmya/wheat_0425/ABD_Genome.20170209.fa
@userLibs               = /home/rui/sowmya/wheat_0425/WheatsRNA_tagcount.txt

The phasis.set I had today:
@reference              = ABD_Genome.20170209.fa
@userLibs               = WheatsRNA_tagcount.txt

And the problem was fixed. I think it's because I added the full path to the setting file, which is not correct. Thank you so much for all the help!

But after I ran:  python3 phasmerge -mode merge -dir phased_04_26_21_06
I got some new error messages. I'll put them in a new thread. 
Thanks!

**Comment by atulkakrana** [comment] 2017-04-27 14:10
I am glad that changing the directories worked out. Although I have mentioned in the wiki to keep input files in the same directory, I guess I need to mention to avoid using long paths. These work well on our machines, so we will still test this report.

Thanks for helping with troubleshooting. I am closing this bug.

Atul

**Closed by atulkakrana** 2017-04-27 14:10 UTC
